version: "3.8"

services:

  traefik:
    image: "traefik:v2.5"
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.constraints=Label(`crowsnest.expose`, `true`)"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.mqtt.address=:1883"
      - "--entrypoints.traefik-dashboard.address=:8080"
      - "--entrypoints.emqx-dashboard.address=:8081"
    # Dynamic Configuration
    labels:
      - "crowsnest.expose=true"
      - "traefik.http.routers.traefik-dashboard.rule=(PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik-dashboard.entryPoints=traefik-dashboard"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
    ports:
      - "${CROWSNEST_EXTERNAL_HTTP_PORT:-80}:80"
      - "${CROWSNEST_EXTERNAL_MQTT_TCP_PORT:-1883}:1883"
      - "${CROWSNEST_EXTERNAL_TRAEFIK_DASHBOARD_PORT:-0}:8080"
      - "${CROWSNEST_EXTERNAL_EMQX_DASHBOARD_PORT:-0}:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  emqx:
    image: emqx/emqx
    restart: unless-stopped
    environment:
      - EMQX_NAME=crowsnest
      - EMQX_HOST=127.0.0.1
      - EMQX_ACL_NOMATCH=allow
      - EMQX_ACL_FILE=etc/not-available.conf
      - EMQX_MQTT__MAX_PACKET_SIZE=10MB
    labels:
      - "crowsnest.expose=true"
      - "traefik.tcp.routers.emqx-tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.emqx-tcp.entryPoints=mqtt"
      - "traefik.tcp.routers.emqx-tcp.service=emqx-tcp-service"
      - "traefik.tcp.services.emqx-tcp-service.loadbalancer.server.port=1883"
      - "traefik.http.routers.emqx-ws.rule=PathPrefix(`/mqtt`)"
      - "traefik.http.routers.emqx-ws.entryPoints=web"
      - "traefik.http.routers.emqx-ws.service=emqx-ws-service"
      - "traefik.http.services.emqx-ws-service.loadbalancer.server.port=8083"
      - "traefik.tcp.routers.emqx-dashboard.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.emqx-dashboard.entryPoints=emqx-dashboard"
      - "traefik.tcp.routers.emqx-dashboard.service=emqx-dashboard-service"
      - "traefik.tcp.services.emqx-dashboard-service.loadbalancer.server.port=18083"

  rtsp:
    image: docker.io/aler9/rtsp-simple-server:latest
    restart: unless-stopped
    network_mode: "host"