version: '3'
services:

  SDR-RTL-AIS:
    image: ghcr.io/bklofas/rtl-ais:latest
    restart: unless-stopped
    network_mode: "host"
    devices:
      - "/dev/bus/usb"
    command: "./rtl_ais -d 0 -h 127.0.0.1 -P 10110"

  AIS-connector:
    image: ghcr.io/mo-rise/crowsnest-toolbox:v0.4.2
    restart: unless-stopped
    network_mode: "host"
    command:
      [
        "socat -u UDP4-RECV:10110,reuseaddr STDOUT | b64_encode | raw_to_brefv | mosquitto_pub -l -t 'CROWSNEST/SEAHORSE/RAW/AIS'"
      ]

  AIS-decoder:
    image: ghcr.io/mo-rise/crowsnest-processor-ais-decode:v0.1.2
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MQTT_BROKER_HOST=localhost
      - MQTT_BROKER_PORT=1883
      - MQTT_INPUT_TOPIC=CROWSNEST/SEAHORSE/RAW/AIS
      - MQTT_OUTPUT_BASE_TOPIC=CROWSNEST/SEAHORSE/AIS
