version: "3"
services:
  multicast-nmea:
    image: ghcr.io/mo-rise/crowsnest-connector-udp-nmea:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MCAST_GRP=239.192.0.3
      - MCAST_PORT=60003
      - MQTT_TOPIC_RAW=CROWSNEST/SEAHORSE/GNSS/0/RAW
      - MQTT_TOPIC_JSON=CROWSNEST/SEAHORSE/GNSS/0/JSON